Refactor - non dev mode, disk space limits and file naming
World-Meteorological-Organization/wis2downloader-v1 pull request #18
Opened 2024-06-10 08:45 UTC by david-i-berry

Changes to address 

- #12 
- #13
- #14 
- #15

Other changes

- updated readme
- addition of GET, POST and DELETE for managing subscriptions
- OpenAPI / Swagger documentation added,.

2024-06-10 10:45 UTC, maaikelimper commented
Please add an when WIS2DOWNLOADER_CONFIG is not yet or the app crashes here:

https://github.com/wmo-im/wis2downloader/blob/minor-fixes/wis2downloader/utils/config.py#L9-L10

2024-06-10 11:24 UTC, maaikelimper commented
Please document the unit for max_disk_usage and which disk it relates to

2024-06-10 12:28 UTC, maaikelimper commented
I added one commit to allow testing with a non SSL secured client

2024-06-10 14:54 UTC, maaikelimper requested changes

2024-06-10 14:54 UTC, maaikelimper commented on wis2downloader/app.py
> +    topic = request.args.get('topic')
Why are you getting the topic as an argument in the POST-request ? I was expecting a POST-request to mean the user would post the topic in the data being posted ?

2024-06-10 14:54 UTC, maaikelimper commented on wis2downloader/utils/config.py
> +    config_file = Path(config_file)
this crashes downloader when WIS2DOWNLOADER_CONFIG is not defined, please print an error so the user knows this a required env variable

2024-06-10 15:23 UTC, david-i-berry commented on wis2downloader/app.py
> +    topic = request.args.get('topic')
Good point, I'll update. 

Should it be POST or PUT and can I remove the GET option?

2024-06-10 15:30 UTC, maaikelimper commented on wis2downloader/app.py
> +    topic = request.args.get('topic')
Use POST and you can remove the GET option, this should also remove the need to deal with special characters like + and #

Maybe you also want to POST a request to remove a subscription rather than deleting with an argument (and having to deal with + and # when deleting!)

2024-06-11 11:26 UTC, david-i-berry commented on wis2downloader/app.py
> +    topic = request.args.get('topic')
Changes made, I've left the DELETE to unsubscribe and removed the GETs where appropriate..

2024-06-11 11:26 UTC, david-i-berry commented on wis2downloader/utils/config.py
> +    config_file = Path(config_file)
done

2024-06-11 11:28 UTC, david-i-berry commented
> Please document the unit for max_disk_usage and which disk it relates to

Done, see also #16.

2024-06-11 13:54 UTC, maaikelimper commented
Please add an option to disable pywis_topics-validation, I am unsure if this package is ready to be used for topic-validation at this stage.

Please ensure the text on the error-message indicates what causes the topic-validation to fail

```
python wis2box-ctl.py execute wis2box downloader add-subscription -t bla                                  
Subscription not added
Error: 400
<!doctype html>
<html lang=en>
<title>400 Bad Request</title>
<h1>Bad Request</h1>
<p>Invalid input (Invalid topic=bla It should not contain special characters, backslashes, or escape codes)</p>
```

2024-06-12 12:24 UTC, maaikelimper requested changes
https://github.com/wmo-im/wis2downloader/blob/minor-fixes/wis2downloader/app.py#L27-L29

can you please add an option to set the loglevel so I can override default loglevel='DEBUG'

2024-06-12 13:14 UTC, maaikelimper approved these changes

2024-06-12 13:30 UTC, merged